server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**
          filters:
            - name: CircuitBreaker
              args:
                name: carServiceCircuitBreaker
                fallbackUri: forward:/fallback/cars

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookingServiceCircuitBreaker
                fallbackUri: forward:/fallback/bookings

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback/payments

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: ./logs/api-gateway.log   # путь к файлу логов (создастся в папке проекта api-gateway)
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
