spring:
  application:
    name: car-service # ??? ???, ??? ??????? ?????? ????? ?????? ???? ???????????? ? Config Server
  config:
    import: configserver:http://localhost:8888 # ????? ?????? Config Server
    # ?????: ????? ????? "optional:", ??? ????????, ??? ?????? ?? ??????????,
    # ???? Config Server ??????????. ??? ????????????? ?????????.

# ???? ?? ??????, ????? ?????? ???? ??? ?????????? Config Server, ???????? ???.
# ???? ?? ??????, ????? ?? ?????????? ???? ??? Config Server (??? ??????????),
# ???????? ??: import: optional:configserver:http://localhost:8888