# src/main/resources/application.yml ??? config-server
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/CarRentProj/config-repo
